config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :personal_records, except: :show

  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users do
    resources :personal_records, only: [:create, :index, :new]
  end

  root to: "pages#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
    elsif user.supervisor_role?
      can :manage, User
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/personal_record.rb
class PersonalRecord < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :personal_records
  # accepts_nested_attributes_for :personal_records
end

# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  first_name             :string
#  last_name              :string
#  birthday               :date
#  city                   :string
#  club_name              :string
#  experience             :date
#

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]

  def index
  end
end

app/controllers/personal_records_controller.rb
class PersonalRecordsController < ApplicationController
  before_action :set_personal_record, only: [:edit, :update, :destroy]
  before_action :set_user, only: [:index, :new, :create]

  def index
    @personal_records = PersonalRecord.all
  end

  def new
    @personal_record = PersonalRecord.new
  end

  def edit
  end

  def create
    @personal_record = @user.personal_records.new(personal_record_params)

    respond_to do |format|
      if @personal_record.save
        format.html { redirect_to user_personal_records_url(@personal_record.user), notice: 'Personal record was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @personal_record.update(personal_record_params)
        format.html { redirect_to user_personal_records_url(@personal_record.user), notice: 'Personal record was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    user = @personal_record.destroy.user
    respond_to do |format|
      format.html { redirect_to user_personal_records_url(user), notice: 'Personal record was successfully destroyed.' }
    end
  end

  private
    def set_personal_record
      @personal_record = PersonalRecord.find(params[:id])
    end

    def set_user
      @user = User.find(params[:user_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def personal_record_params
      params.require(:personal_record).permit(:distance, :time, :date)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit
    @user = User.find(params[:id])
    # @user.personal_records.build unless @user.personal_records.any?
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    redirect_to user_path(@user)
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :birthday, :city, :club_name, :experience)
    # , personal_records_attributes: [:id, :distance, :time, :date])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/personal_records_helper.rb
module PersonalRecordsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title RunningClub
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if notice
      %p.notice= notice
    - if alert
      %p.alert= alert
    .container
      = yield

app/views/pages/index.html.haml
- if user_signed_in?
  = link_to 'Edit registration', edit_user_registration_path
  = link_to 'Log out', destroy_user_session_path, method: :delete
  -# = link_to user_index_path, 'Go to App', class: 'login-button'
- else
  = link_to 'Sign in', new_user_session_path, class: 'login-button'
  = link_to 'Register', new_user_registration_path

app/views/personal_records/_form.html.haml
= form_for [@user, @personal_record] do |f|
  - if @personal_record.errors.any?
    #error_explanation
      %h2= "#{pluralize(@personal_record.errors.count, "error")} prohibited this personal_record from being saved:"
      %ul
        - @personal_record.errors.full_messages.each do |message|
          %li= message
  .form-group.row
    .col-md-6
      = f.label "Distance"
      = f.text_field :distance, class: "form-control"
  .form-group.row
    .col-md-6
      = f.label "Time"
      = f.time_field :time, class: "form-control"
  .form-group.row
    .col-md-6
      = f.label "Date"
      = f.date_field :date, class: "form-control", max: Date.today
  .actions
    = f.submit 'Save', class: "btn btn-primary"

app/views/personal_records/edit.html.haml
%h1 Edit your personal record

= render 'form'

= link_to 'Back', user_personal_records_path(@personal_record.user)

app/views/personal_records/index.html.haml
%h1 Personal records
= link_to 'Back to user page', user_path(@user)

%table.table
  %thead
    %tr
      %th Distance
      %th Time
      %th Date
      %th
      %th

  %tbody
    - @personal_records.each do |personal_record|
      %tr
        %td= personal_record.distance
        %td= personal_record.time
        %td= personal_record.date
        %td= link_to 'Edit', edit_personal_record_path(personal_record)
        %td= link_to 'Destroy', personal_record_path(personal_record), method: :delete, data: { confirm: 'Are you sure?' }

= link_to 'New Personal Record', new_user_personal_record_path

app/views/personal_records/new.html.haml
%h1 New personal_record

= render 'form'

= link_to 'Back', user_personal_records_path(@user)

app/views/users/edit.html.haml
.row
  .col-12
    %h1 Users#edit
= form_for @user do |f|
  .form-group.row
    .col-md-6
      = f.label "First Name"
      = f.text_field :first_name, class: "form-control"

  .form-group.row
    .col-md-6
      = f.label "Last Name"
      = f.text_field :last_name, class: "form-control"

  .form-group.row
    .col-md-6
      = f.label "Birthday"
      = f.date_field :birthday, class: "form-control", max: Date.today

  .form-group.row
    .col-md-6
      = f.label "City"
      = f.text_field :city, class: "form-control"

  .form-group.row
    .col-md-6
      = f.label "Club name"
      = f.text_field :club_name, class: "form-control"

  .form-group.row
    .col-md-6
      = f.label "Experience"
      = f.date_field :experience, class: "form-control", max: Date.today

  = f.submit "save", class: "btn btn-primary"

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.haml
%p First name: #{@user.first_name}
%p Last name: #{@user.last_name}

%p Birthday: #{@user.birthday}
%p City: #{@user.city}

%p Club name: #{@user.club_name}
%p Experience: #{@user.experience}

- if @user.personal_records.any?
  %table.table
    %caption
      Personal Records
      = link_to "Add new record", new_user_personal_record_path(@user)
    %thead.thead-light
      %tr
        %th Distance
        %th Time
        %th Date
        %th
    %tbody
      - @user.personal_records.each do |record|
        %tr
          %td #{record.distance}
          %td #{record.time}
          %td #{record.date}
          %td= link_to 'Edit', edit_personal_record_path(record)

= link_to "Edit user", edit_user_path(@user), class: 'btn btn-primary'